version: '3.5'

services:
  postgres1:
    image: arm64v8/postgres:12.6
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: pg12
      POSTGRES_PASSWORD: pg12
      PGDATA: /data/postgres
    volumes:
      - "postgres_data_1:/data/postgres"
    ports:
      - "5432:5432"
    networks:
      - pg12
    restart: unless-stopped
  postgres2:
    image: arm64v8/postgres:12.6
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: pg12
      POSTGRES_PASSWORD: pg12
      PGDATA: /data/postgres
    volumes:
      - "postgres_data_2:/data/postgres"
    ports:
      - "5433:5432"
    networks:
      - pg12
    restart: unless-stopped
  zookeeper:
    image: wurstmeister/zookeeper
    volumes:
      - zookeeper_data:/data
    ports:
      - 2182:2182
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_CREATE_TOPICS: "hotel-bookings"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    volumes:
      - kafka_data:/kafka
    depends_on:
      - zookeeper
networks:
  pg12:
    driver: bridge

volumes:
  postgres_data_1:
  postgres_data_2:
  zookeeper_data:
  kafka_data: